services:
  - type: web
    name: emaktab-site
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false # User will provide this manually from Neon or other provider
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
