services:
  - type: web
    name: emaktab-site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emaktab-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: emaktab-db
    plan: free
